next starter kit - ESM & Vite
apostrophecms/starter-kit-ecommerce pull request #25
Opened 2024-11-08 11:34 UTC by myovchev

## Summary

The next branch is the official next release of the starter kit - ESM + Vite build.

## What are the specific steps to test this change?

*For example:*
> 1. Run the website and log in as an admin
> 2. Open a piece manager modal and select several pieces
> 3. Click the "Archive" button on the top left of the manager and confirm that it should proceed
> 4. Check that all pieces have been archived properly

## What kind of change does this PR introduce?
*(Check at least one)*

- [ ] Bug fix
- [ ] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [ ] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [ ] The changelog is updated
- [ ] Related documentation has been updated
- [ ] Related tests have been updated

If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

2024-11-08 11:37 UTC, myovchev commented on package.json
> +    "apostrophe": "github:apostrophecms/apostrophe#pro-6694-breakpoint-preview-vite-ready",
FIXME: both dependency version when everything is released.

2024-11-11 10:40 UTC, haroun requested changes

2024-11-11 10:40 UTC, haroun commented on docs/developer/getting-started.md
> +1. If you haven't already, install the [Apostrophe CLI tool](https://v3.docs.apostrophecms.org/guide/setting-up.html#the-apostrophe-cli-tool) using
```suggestion
1. If you haven't already, install the [Apostrophe CLI tool](https://docs.apostrophecms.org/guide/setting-up.html#the-apostrophe-cli-tool) using
```

2024-11-11 12:25 UTC, myovchev commented on package.json
> +    "apostrophe": "github:apostrophecms/apostrophe",
FIXME: revert back to versions after release

2024-11-12 16:42 UTC, haroun approved these changes

2024-12-18 19:07 UTC, merged